### ISSUE TITLE
featuretable for R version 4.1

### ISSUE THREAD

**Issue by Vetshweta** [mooreryan/featuretable#2]
Hi, I tried to install featuretable for r version 4.1.0 but its not working. Could you please help me install it?

**Comment by mooreryan** [comment]
I just tested the installation of FeatureTable on R version 4.1.0 using [this docker image](https://hub.docker.com/layers/rocker/r-ver/4.1.0/images/sha256-1334e769e5a06c1e334e9ae90a4029b1cff3d1c7ce566b50e660b1909a882fa8?context=explore), which uses Debian Stretch, and had no problems.  What problems are you having?

I just updated the install instructions on [the release page](https://github.com/mooreryan/featuretable/releases/tag/v0.0.10), but I will paste them here for reference as well:

## Install instructions

If you don't have R6 and rlang packages installed, you will need to install them first.

```R
install.packages(c('R6', 'rlang'))
```

Then download the source package from this release page. Finally, install the source package like so:

```R
install.packages("/path/to/featuretable_0.0.10.tar.gz", repos = NULL)
```
